$(eval $(call addlib,app_sgx_driver))

APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_main.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_page_cache.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_ioctl.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_vma.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_util.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_encl.c
APP_SGX_DRIVER_SRCS-y += $(APP_SGX_DRIVER_BASE)/sgx_encl2.c
